### ISSUE TITLE
[Native/Emscripten] Webapp down

### ISSUE THREAD

**Issue by Houkime** [Zany80/Zany80.github.io#3]
blue-green screen and that's it.
v2 works ok

Affected browsers: 

- Falkon 3.0.1 (QtWebEngine)
- Firefox 63.0.3

**Comment by pixelherodev** [comment]
Blue green screen? That's what it's supposed to show.

It's just a completely blank background?

**Comment by pixelherodev** [comment]
Can you check the JS console for an error log?

**Comment by Houkime** [comment]
yep.
v2 shows menus and stuff, v3 doesn't

![image](https://user-images.githubusercontent.com/32805122/49521765-0f4c9b00-f89e-11e8-8f63-465d2f0741ed.png)

```
trap!
printErr @ (index):35

```

**Comment by pixelherodev** [comment]
Thanks for pointing this out, give me a few minutes.

The problem isn't on your end, the site was automatically updated from modified code last night, but I hadn't finished the code when I saved it so there's a missing bit which causes a crash.

Give me a few minutes and I'll manually update the site.

**Comment by pixelherodev** [comment]
Should be up in a minute or two, just need to give Github a chance to refresh it.

**Comment by pixelherodev** [comment]
Hold on, GitHub is being weird with the BIOS ROM, working on it...

**Comment by pixelherodev** [comment]
Got it.

**Comment by pixelherodev** [comment]
![image](https://user-images.githubusercontent.com/10342579/49524976-c33c2f00-f87a-11e8-83ff-6643b46a62d5.png)
Working now, right?

**Comment by Houkime** [comment]
yep. all is ok.
